DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  department TEXT NOT NULL,
  start_date TEXT NOT NULL,
  status TEXT CHECK(status IN ('ENROLLED','INACTIVE')) DEFAULT 'ENROLLED',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
